# Generated by Django 2.2 on 2020-09-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_productname_capitalize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttag',
            old_name='products',
            new_name='product',
        ),
    ]
